### ISSUE TITLE
add healthchecks to docker-compose files

### ISSUE THREAD

**Issue by simeon-s1** [rki-mf1/sonar#39]
occasionally the backend will start up too fast so the db is not ready yet:
![grafik](https://github.com/user-attachments/assets/8d3db0aa-18b9-40d5-92a9-b91b1f972603)

This can be prevented with a healthcheck like 

```
postgres:
    [...]
    healthcheck:
          test: ["CMD", "pg_isready", "-q"]
[...]
dev-django:
    [...]
    depends_on:
      - postgres:
        condition: service_healthy
```

[stackoverflow](https://stackoverflow.com/questions/62904304/psycopg2-operationalerror-fatal-the-database-system-is-starting-up-docker)

[docker docs] (https://docs.docker.com/compose/compose-file/#healthcheck)
